name: Test
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache purescript dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            .spago
            ${{ env.spago_global_cache }}
            output
          key: >-
            ${{ hashFiles('package-lock.json') }}-
            ${{ hashFiles('spago.dhall') }}-
            ${{ hashFiles('packages.dhall') }}
      - name: Install dependencies
        run: npm ci --loglevel verbose
      - name: Build ps
        run: npx spago build
